"""add lesson_plans and lesson_plan_references tables

Revision ID: 1b6dd46c3766
Revises: add_token_blacklist_001
Create Date: 2026-03-14 09:35:52.343814



"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b6dd46c3766'
down_revision: Union[str, None] = 'add_token_blacklist_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_session_id'), 'lesson_plans', ['session_id'], unique=True)
    op.create_index(op.f('ix_lesson_plans_user_id'), 'lesson_plans', ['user_id'], unique=False)
    op.create_table('lesson_plan_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_plan_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plan_references_lesson_plan_id'), 'lesson_plan_references', ['lesson_plan_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_references_user_id'), 'lesson_plan_references', ['user_id'], unique=False)
    op.alter_column('knowledge_assets', 'library_id',
               existing_type=sa.INTEGER(),
               comment='所属知识库',
               existing_nullable=True)
    op.alter_column('knowledge_assets', 'vector_status',
               existing_type=sa.VARCHAR(length=20),
               comment='向量化状态: pending/processing/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('token_blacklist', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='Token SHA256 哈希',
               existing_nullable=False)
    op.alter_column('token_blacklist', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Token 原始过期时间',
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment='是否为系统管理员',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               comment='Token 版本号，修改密码时+1使所有旧token失效',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Token 版本号，修改密码时+1使所有旧token失效',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为系统管理员',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('token_blacklist', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Token 原始过期时间',
               existing_nullable=False)
    op.alter_column('token_blacklist', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Token SHA256 哈希',
               existing_nullable=False)
    op.alter_column('knowledge_assets', 'vector_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='向量化状态: pending/processing/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('knowledge_assets', 'library_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属知识库',
               existing_nullable=True)
    op.drop_index(op.f('ix_lesson_plan_references_user_id'), table_name='lesson_plan_references')
    op.drop_index(op.f('ix_lesson_plan_references_lesson_plan_id'), table_name='lesson_plan_references')
    op.drop_table('lesson_plan_references')
    op.drop_index(op.f('ix_lesson_plans_user_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_session_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    # ### end Alembic commands ###
