"""add file fields to courseware table

Revision ID: 86c4f56b734d
Revises: add_ppt_template_style_001
Create Date: 2026-04-06 15:57:28.851158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c4f56b734d'
down_revision: Union[str, None] = 'add_ppt_template_style_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courseware', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('courseware', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('courseware', sa.Column('file_type', sa.String(length=20), nullable=True))
    op.add_column('courseware', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('courseware', sa.Column('remark', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courseware', 'remark')
    op.drop_column('courseware', 'tags')
    op.drop_column('courseware', 'file_type')
    op.drop_column('courseware', 'file_size')
    op.drop_column('courseware', 'file_name')
    # ### end Alembic commands ###
