"""add parsed_content to ppt_reference_files

Revision ID: af23f6adc6da
Revises: add_renovation_fields_001
Create Date: 2026-04-07 23:37:20.574272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af23f6adc6da'
down_revision: Union[str, None] = 'add_renovation_fields_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ppt_project_intents_project_id'), 'ppt_project_intents', type_='unique')
    op.create_index(op.f('ix_ppt_project_intents_project_id'), 'ppt_project_intents', ['project_id'], unique=True)
    op.add_column('ppt_reference_files', sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppt_reference_files', 'parsed_content')
    op.drop_index(op.f('ix_ppt_project_intents_project_id'), table_name='ppt_project_intents')
    op.create_unique_constraint(op.f('uq_ppt_project_intents_project_id'), 'ppt_project_intents', ['project_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
