"""add_user_profile_fields

Revision ID: f258ec926a55
Revises: add_lib_tags_001
Create Date: 2026-03-29 00:51:00.484044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f258ec926a55'
down_revision: Union[str, None] = 'add_lib_tags_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subject', sa.String(length=100), nullable=True, comment='任教科目'))
    op.add_column('users', sa.Column('school', sa.String(length=200), nullable=True, comment='学校名称'))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True, comment='工号'))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True, comment='专业简介'))
    op.add_column('users', sa.Column('two_fa_enabled', sa.Boolean(), nullable=False, server_default='false', comment='是否启用2FA邮箱验证'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'two_fa_enabled')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'school')
    op.drop_column('users', 'subject')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
